-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "overview" DROP NOT NULL,
ALTER COLUMN "posterURL" DROP NOT NULL,
ALTER COLUMN "showId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Show" ALTER COLUMN "showId" DROP NOT NULL;
